// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUU948DatcvyhZ2O5bVfzxrU-xj0DCRls',
    appId: '1:327860192846:web:70dfedf0f2a79cbc85651f',
    messagingSenderId: '327860192846',
    projectId: 'booktrackerapp-325b9',
    authDomain: 'booktrackerapp-325b9.firebaseapp.com',
    storageBucket: 'booktrackerapp-325b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA4zJoB71pv3jz62y3KswW5TuFnAP2Lec',
    appId: '1:327860192846:android:4a9510c6640f66ff85651f',
    messagingSenderId: '327860192846',
    projectId: 'booktrackerapp-325b9',
    storageBucket: 'booktrackerapp-325b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKOhswFI90EgfLGC-4RKFULk74lRyYNQA',
    appId: '1:327860192846:ios:f853469486d97f4c85651f',
    messagingSenderId: '327860192846',
    projectId: 'booktrackerapp-325b9',
    storageBucket: 'booktrackerapp-325b9.appspot.com',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKOhswFI90EgfLGC-4RKFULk74lRyYNQA',
    appId: '1:327860192846:ios:251967d6f3debdbd85651f',
    messagingSenderId: '327860192846',
    projectId: 'booktrackerapp-325b9',
    storageBucket: 'booktrackerapp-325b9.appspot.com',
    iosBundleId: 'com.example.budgetApp.RunnerTests',
  );
}
